### ISSUE TITLE
 activation rules for constraints not working for programming by contract

### ISSUE THREAD

**Issue by spik3r** [sebthom/oval#7] opened 2017-05-17 05:12 UTC
Activation rules don't seem to work when using Programming by contract with AspectJ.
As per the documentation this works when using a Validator:

    public class BusinessObject {
        private String fieldA;
        
        @NotNull(when = "javascript:_this.fieldA != null")
        private String fieldB;
        
        public BusinessObject(){}
        
        public BusinessObject(String fieldA, String fieldB) {
            this.fieldA = fieldA;
            this.fieldB = fieldB;
        }
        
        public String getFieldA() {
            return this.fieldA;
        }
        public void setFieldB(String fieldB) {
            this.fieldB = fieldB;
        }
    }

But applying the same concept using Guarded does not.

    @Guarded
    public class Pojo {
        private String fieldA;
        private String fieldB;
        
        public Pojo(
                String fieldA,
                @NotNull(when = "javascript:_this.fieldA != null") String fieldB) {
            
            this.fieldA = fieldA;
            this.fieldB = fieldB;
        }
        
        public String getFieldA() {
            return this.fieldA;
        }
    }

**Comment by sebthom** [comment] 2017-05-17 15:45
Your example does not work because `_this` is a reference to the object you are about to create. The `when` expression is checked before the value of the argument `fieldA` is assigned to the field `this.fieldA`.

Activation of a parameter constraint depending on another parameter's value is currently not possible.

You can try using a `@PostValidateThis` constraint, e.g.
```java
@Guarded
public class Pojo {
    private String fieldA;

    @NotNull(when = "javascript:_this.fieldA != null")
    private String fieldB;
    
    @PostValidateThis
    public Pojo(String fieldA, String fieldB) {
        this.fieldA = fieldA;
        this.fieldB = fieldB;
    }
    
    public String getFieldA() {
        return this.fieldA;
    }
}
```

**Comment by spik3r** [comment] 2017-05-18 03:34
Hi Sebastian,
thanks for your quick response, unfortunately your code snipped doesn't work for me and throws a `java.lang.StackOverflowError`, unless I remove the getter. Unfortunately if I do that the JavaScript can't find the variable anymore

Is there some limitation to using `@PostValidateThis`?
It seems to only work when there is no `when` expression.
I think there may be a bug when using `@PostValidateThis` with `when` and either a public variable or getter since this exact combination always throws a `java.lang.StackOverflowError` even in a another example (slightly modified version of the example from 4.4.4 of the OVal documentation)


    @Guarded
    public class MethodPostValidation {
        
        private boolean someVariable = true;
    
        @MaxLength(value = 10)
    //    @MaxLength(value = 10, when = "javascript:_this.someVariable == true") // Uncomment this to get StackOverflowError
        private String name = "12345";
        
        MethodPostValidation(){}
        
        MethodPostValidation(boolean someVariable) {
            this.someVariable = someVariable;
        }
        
        @PostValidateThis
        public void appendToName(String appendix) {
            name += appendix;
        }
        
        public boolean getSomeVariable() {
            return this.someVariable;
        }
    }

Basic example tests:


    public class MethodPostValidationTest {
        @Test(expected = ConstraintsViolatedException.class)
        public void getFieldTooLongThrowsException() throws Exception {
            MethodPostValidation methodPostValidation = new MethodPostValidation();
            methodPostValidation.appendToName("asdfghjkl");
            
        }
        
        @Test
        public void getFieldSomeVariableFalseDoesNotValidateNoException() throws Exception {
            MethodPostValidation methodPostValidation = new MethodPostValidation(false);
            methodPostValidation.appendToName("asdfghjkl");
        }
    }

**Comment by sebthom** [comment] 2017-05-19 16:58
I think this is a problem with Javascript itself. Looks like you cannot access private variables. Rhino does not throw an exception but simply evaluates the formula as false. This it never activates.

Try this same with groovy instead.

**Comment by sebthom** [comment] 2017-05-19 17:17
I cannot really reproduce the issue. I extended the respective test case and it seems to work fine, see https://github.com/sebthom/oval/commit/c676ef2f1880050255661a8eb126f432134de784

There are two things you need to be aware of:
1) The JavaScript Engine Rhino cannot directly access private fields. E.g. something like `"javascript:_this.myPrivateField != null && _this.myPrivateField.length > 10"` will always return false, no matter the value of the private field. Rhino apparently does not raise an exception if it cannot access the private field. I would recommend you to use groovy instead of javascript for constraint activation.
1) For most scripting runtimes (including JavaScript) the statement `_this.someVariable` will result in the invocation of the `_this.getSomeVariable()` getter and not in a direct access of a private field with the same name.

**Comment by spik3r** [comment] 2017-05-20 23:09
Hi Sebastian, 
thanks again.

I noticed that javascript couldn't see private variables for some reason.
I've got it working using `@PostValidateThis` as long as I add `@Guarded(checkInvariants = false)` otherwise I get a `StackOverflowError` from the getters.


    @Guarded(checkInvariants = false)// removing this results in StackOverflowError
    public class User {
        private final String firstName;
        private final String lastName;
        @NotNull(when = "groovy:_this.lastName != null")
        private final Integer age;

        @PostValidateThis
        public User(String firstName, String lastName, Integer age) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.age = age;
        }

        public String getFirstName() {
            return firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public Integer getAge() {
            return age;
        }
    }

**Comment by sebthom** [comment] 2017-05-22 11:05
I added a fix for the StackOverflowError. Can you please give the latest snapshot a try: http://oval.sourceforge.net/mvn-repo/snapshot/net/sf/oval/oval/1.88-SNAPSHOT/

**Comment by spik3r** [comment] 2017-05-22 23:15
I've tested the latest snapshot and can confirm I no longer get the StackOverflowError.
Thanks again for the quick fix.

**Closed** 2017-05-22 23:18 UTC
